//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIX_STAN789_T
    {
        public decimal ID { get; set; }
        public System.DateTime WHEN { get; set; }
        public Nullable<decimal> N_STAN { get; set; }
        public Nullable<bool> START_STOP { get; set; }
        public Nullable<bool> ERASE { get; set; }
        public Nullable<bool> BREAK { get; set; }
        public Nullable<bool> REPLAC { get; set; }
        public Nullable<int> COUNTER { get; set; }
        public System.DateTime INCOMIN_DATE { get; set; }
        public string G_UCHASTOK { get; set; }
    }
}
