//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibOracle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OraContext : DbContext
    {
        public OraContext()
            : base("name=OraContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_INSERT_STAN(string g_UCHASTOK_VAR, Nullable<decimal> n_STAN_VAR, Nullable<decimal> sTART_STOP_VAR, Nullable<decimal> eRASE_VAR, Nullable<decimal> bREAK_VAR, Nullable<decimal> rEPLAC_VAR, Nullable<decimal> cOUNTER_VAR, Nullable<System.DateTime> iNCOMIN_DATE_VAR)
        {
            var g_UCHASTOK_VARParameter = g_UCHASTOK_VAR != null ?
                new ObjectParameter("G_UCHASTOK_VAR", g_UCHASTOK_VAR) :
                new ObjectParameter("G_UCHASTOK_VAR", typeof(string));
    
            var n_STAN_VARParameter = n_STAN_VAR.HasValue ?
                new ObjectParameter("N_STAN_VAR", n_STAN_VAR) :
                new ObjectParameter("N_STAN_VAR", typeof(decimal));
    
            var sTART_STOP_VARParameter = sTART_STOP_VAR.HasValue ?
                new ObjectParameter("START_STOP_VAR", sTART_STOP_VAR) :
                new ObjectParameter("START_STOP_VAR", typeof(decimal));
    
            var eRASE_VARParameter = eRASE_VAR.HasValue ?
                new ObjectParameter("ERASE_VAR", eRASE_VAR) :
                new ObjectParameter("ERASE_VAR", typeof(decimal));
    
            var bREAK_VARParameter = bREAK_VAR.HasValue ?
                new ObjectParameter("BREAK_VAR", bREAK_VAR) :
                new ObjectParameter("BREAK_VAR", typeof(decimal));
    
            var rEPLAC_VARParameter = rEPLAC_VAR.HasValue ?
                new ObjectParameter("REPLAC_VAR", rEPLAC_VAR) :
                new ObjectParameter("REPLAC_VAR", typeof(decimal));
    
            var cOUNTER_VARParameter = cOUNTER_VAR.HasValue ?
                new ObjectParameter("COUNTER_VAR", cOUNTER_VAR) :
                new ObjectParameter("COUNTER_VAR", typeof(decimal));
    
            var iNCOMIN_DATE_VARParameter = iNCOMIN_DATE_VAR.HasValue ?
                new ObjectParameter("INCOMIN_DATE_VAR", iNCOMIN_DATE_VAR) :
                new ObjectParameter("INCOMIN_DATE_VAR", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_STAN", g_UCHASTOK_VARParameter, n_STAN_VARParameter, sTART_STOP_VARParameter, eRASE_VARParameter, bREAK_VARParameter, rEPLAC_VARParameter, cOUNTER_VARParameter, iNCOMIN_DATE_VARParameter);
        }
    }
}
